"""Type stubs for pygamlastan - Python bindings for the gamlastan SAML 2.0 library.

This is a PEP 561 stub-only package describing the compiled extension and its
submodules (core, xml, crypto, bindings, metadata, security, profiles,
attribute_map, idp).
"""

from . import (
    attribute_map as attribute_map,
    bindings as bindings,
    core as core,
    crypto as crypto,
    idp as idp,
    logout as logout,
    metadata as metadata,
    profiles as profiles,
    security as security,
    xml as xml,
)

__version__: str

class SamlError(Exception): ...
class SamlCoreError(SamlError): ...
class SamlXmlError(SamlError): ...
class SamlCryptoError(SamlError): ...
class SamlBindingError(SamlError): ...
class SamlMetadataError(SamlError): ...
class SamlSecurityError(SamlError): ...
class SamlProfileError(SamlError): ...
class SamlPolicyError(SamlError): ...
class SamlIdentError(SamlError): ...
