from .core import Attribute, NameId

EPTID_OID: str

class AttributeConverter:
    def __init__(self, name_format: str) -> None: ...
    @staticmethod
    def from_static(name: str) -> AttributeConverter: ...
    def add_mapping(self, wire: str, local: str) -> None: ...
    @property
    def name_format(self) -> str: ...
    def to_local_name(self, wire_name: str) -> str | None: ...
    def to_wire_name(self, local_name: str) -> str | None: ...

class LocalAttribute:
    def __init__(self, name: str, values: list[str]) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def values(self) -> list[str]: ...

class AttributeConverterSet:
    @staticmethod
    def with_default_maps(allow_unknown_attributes: bool = ...) -> AttributeConverterSet: ...
    def to_local(self, attributes: list[Attribute]) -> list[LocalAttribute]: ...
    def from_local(self, ava: list[LocalAttribute], name_format: str) -> list[Attribute]: ...
    def local_name(self, attribute: Attribute) -> str | None: ...

def eptid_attribute(name_ids: list[NameId]) -> Attribute: ...
def eptid_name_ids(attribute: Attribute) -> list[NameId]: ...
