from collections.abc import Mapping, Sequence
from typing import Protocol

from .crypto import SamlSigner

RELAY_STATE_MAX_BYTES: int

class ArtifactStoreProtocol(Protocol):
    def store(self, artifact: str, message_xml: bytes) -> None: ...
    def resolve_and_consume(self, artifact: str) -> bytes | None: ...
    def store_for_recipient(
        self, artifact: str, recipient_entity_id: str, message_xml: bytes
    ) -> None: ...
    def resolve_and_consume_for_requester(
        self, artifact: str, requester_entity_id: str
    ) -> bytes | None: ...

class RedirectDecoded:
    @property
    def saml_xml(self) -> bytes: ...
    @property
    def saml_text(self) -> str: ...
    @property
    def is_request(self) -> bool: ...
    @property
    def relay_state(self) -> str | None: ...
    @property
    def sig_alg(self) -> str | None: ...
    @property
    def signature(self) -> bytes | None: ...
    @property
    def signature_input(self) -> str | None: ...

class PostDecoded:
    @property
    def saml_xml(self) -> bytes: ...
    @property
    def saml_text(self) -> str: ...
    @property
    def is_request(self) -> bool: ...
    @property
    def relay_state(self) -> str | None: ...

class SamlArtifact:
    def __init__(self, endpoint_index: int, entity_id: str, random_handle: bytes) -> None: ...
    @staticmethod
    def generate(endpoint_index: int, entity_id: str) -> SamlArtifact: ...
    @staticmethod
    def decode(encoded: str) -> SamlArtifact: ...
    def encode(self) -> str: ...
    def matches_entity(self, entity_id: str) -> bool: ...
    @property
    def endpoint_index(self) -> int: ...
    @property
    def source_id(self) -> bytes: ...
    @property
    def message_handle(self) -> bytes: ...

def redirect_encode(saml_xml: bytes, is_request: bool, destination: str, relay_state: str | None = ..., signer: SamlSigner | None = ..., sig_alg: str | None = ..., unsafe_allow_weak_sha1: bool = ...) -> str: ...
def redirect_decode(query: str, base_url: str = ...) -> RedirectDecoded: ...
def post_encode(saml_xml: bytes, is_request: bool, destination: str, relay_state: str | None = ...) -> str: ...
def post_decode(form_params: Sequence[tuple[str, str]] | Mapping[str, str], url: str = ..., unsafe_allow_collapsed_form: bool = ...) -> PostDecoded: ...
def validate_relay_state(value: str) -> None: ...
