from datetime import datetime
from typing import Any

# --- constants (subset; all are str) ---
BINDING_SOAP: str
BINDING_PAOS: str
BINDING_HTTP_REDIRECT: str
BINDING_HTTP_POST: str
BINDING_HTTP_ARTIFACT: str
BINDING_URI: str
NAMEID_UNSPECIFIED: str
NAMEID_EMAIL: str
NAMEID_X509: str
NAMEID_WINDOWS: str
NAMEID_ENTITY: str
NAMEID_PERSISTENT: str
NAMEID_TRANSIENT: str
NAMEID_KERBEROS: str
NAMEID_ENCRYPTED: str
CM_BEARER: str
CM_HOLDER_OF_KEY: str
CM_SENDER_VOUCHES: str
STATUS_SUCCESS: str
STATUS_REQUESTER: str
STATUS_RESPONDER: str
STATUS_VERSION_MISMATCH: str
STATUS_AUTHN_FAILED: str
STATUS_NO_AUTHN_CONTEXT: str
STATUS_REQUEST_DENIED: str
STATUS_UNKNOWN_PRINCIPAL: str
AUTHN_CONTEXT_PASSWORD: str
AUTHN_CONTEXT_PASSWORD_PROTECTED_TRANSPORT: str
AUTHN_CONTEXT_UNSPECIFIED: str
AUTHN_CONTEXT_X509: str
AUTHN_CONTEXT_KERBEROS: str
ATTRNAME_FORMAT_UNSPECIFIED: str
ATTRNAME_FORMAT_URI: str
ATTRNAME_FORMAT_BASIC: str
SAML_ASSERTION_NS: str
SAML_PROTOCOL_NS: str
SAML_METADATA_NS: str
XMLDSIG_NS: str
XMLENC_NS: str

def generate_id() -> str: ...
def validate_entity_id(value: str) -> str: ...

class Issuer:
    def __init__(self, value: str, format: str | None = ..., name_qualifier: str | None = ..., sp_name_qualifier: str | None = ...) -> None: ...
    @property
    def value(self) -> str: ...
    @property
    def format(self) -> str | None: ...
    @property
    def name_qualifier(self) -> str | None: ...
    @property
    def sp_name_qualifier(self) -> str | None: ...

class NameId:
    def __init__(self, value: str, format: str | None = ..., name_qualifier: str | None = ..., sp_name_qualifier: str | None = ..., sp_provided_id: str | None = ...) -> None: ...
    @property
    def value(self) -> str: ...
    @property
    def format(self) -> str | None: ...
    @property
    def name_qualifier(self) -> str | None: ...
    @property
    def sp_name_qualifier(self) -> str | None: ...
    @property
    def sp_provided_id(self) -> str | None: ...

class NameIdPolicy:
    def __init__(self, format: str | None = ..., sp_name_qualifier: str | None = ..., allow_create: bool = ...) -> None: ...
    @property
    def format(self) -> str | None: ...
    @property
    def sp_name_qualifier(self) -> str | None: ...
    @property
    def allow_create(self) -> bool: ...

class SubjectConfirmationData:
    @property
    def not_before(self) -> datetime | None: ...
    @property
    def not_on_or_after(self) -> datetime | None: ...
    @property
    def recipient(self) -> str | None: ...
    @property
    def in_response_to(self) -> str | None: ...
    @property
    def address(self) -> str | None: ...

class SubjectConfirmation:
    @property
    def method(self) -> str: ...
    @property
    def name_id(self) -> NameId | None: ...
    @property
    def subject_confirmation_data(self) -> SubjectConfirmationData | None: ...

class Subject:
    @property
    def name_id(self) -> NameId | None: ...
    @property
    def subject_confirmations(self) -> list[SubjectConfirmation]: ...

class AudienceRestriction:
    @property
    def audiences(self) -> list[str]: ...
    def matches(self, entity_id: str) -> bool: ...

class ProxyRestriction:
    @property
    def count(self) -> int | None: ...
    @property
    def audiences(self) -> list[str]: ...

class Conditions:
    @property
    def not_before(self) -> datetime | None: ...
    @property
    def not_on_or_after(self) -> datetime | None: ...
    @property
    def one_time_use(self) -> bool: ...
    @property
    def audience_restrictions(self) -> list[AudienceRestriction]: ...
    @property
    def proxy_restriction(self) -> ProxyRestriction | None: ...

class SubjectLocality:
    @property
    def address(self) -> str | None: ...
    @property
    def dns_name(self) -> str | None: ...

class AuthnContext:
    @property
    def authn_context_class_ref(self) -> str | None: ...
    @property
    def authn_context_decl_ref(self) -> str | None: ...
    @property
    def authenticating_authorities(self) -> list[str]: ...

class AuthnStatement:
    @property
    def authn_instant(self) -> datetime: ...
    @property
    def session_index(self) -> str | None: ...
    @property
    def session_not_on_or_after(self) -> datetime | None: ...
    @property
    def subject_locality(self) -> SubjectLocality | None: ...
    @property
    def authn_context(self) -> AuthnContext: ...

class Attribute:
    def __init__(self, name: str, values: list[str] | None = ..., name_format: str | None = ..., friendly_name: str | None = ...) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def name_format(self) -> str | None: ...
    @property
    def friendly_name(self) -> str | None: ...
    @property
    def values(self) -> list[Any]: ...
    @property
    def string_values(self) -> list[str]: ...

class AttributeStatement:
    @property
    def attributes(self) -> list[Attribute]: ...

class StatusCode:
    @property
    def value(self) -> str: ...
    @property
    def sub_status(self) -> StatusCode | None: ...
    def is_success(self) -> bool: ...

class Status:
    @property
    def status_code(self) -> StatusCode: ...
    @property
    def status_message(self) -> str | None: ...
    @property
    def status_detail(self) -> str | None: ...
    def is_success(self) -> bool: ...

class Assertion:
    @property
    def id(self) -> str: ...
    @property
    def issue_instant(self) -> datetime: ...
    @property
    def issuer(self) -> Issuer: ...
    @property
    def has_signature(self) -> bool: ...
    @property
    def subject(self) -> Subject | None: ...
    @property
    def conditions(self) -> Conditions | None: ...
    @property
    def authn_statements(self) -> list[AuthnStatement]: ...
    @property
    def attribute_statements(self) -> list[AttributeStatement]: ...

class RequestedAuthnContext:
    @property
    def authn_context_class_refs(self) -> list[str]: ...
    @property
    def comparison(self) -> str: ...

class Scoping:
    @property
    def proxy_count(self) -> int | None: ...
    @property
    def idp_list(self) -> list[str]: ...
    @property
    def requester_ids(self) -> list[str]: ...

class AuthnRequest:
    @property
    def id(self) -> str: ...
    @property
    def issue_instant(self) -> datetime: ...
    @property
    def destination(self) -> str | None: ...
    @property
    def issuer(self) -> Issuer | None: ...
    @property
    def has_signature(self) -> bool: ...
    @property
    def name_id_policy(self) -> NameIdPolicy | None: ...
    @property
    def requested_authn_context(self) -> RequestedAuthnContext | None: ...
    @property
    def scoping(self) -> Scoping | None: ...
    @property
    def force_authn(self) -> bool | None: ...
    @property
    def is_passive(self) -> bool | None: ...
    @property
    def assertion_consumer_service_url(self) -> str | None: ...
    @property
    def protocol_binding(self) -> str | None: ...
    @property
    def provider_name(self) -> str | None: ...
    def to_xml(self) -> str: ...

class Response:
    @property
    def id(self) -> str: ...
    @property
    def issue_instant(self) -> datetime: ...
    @property
    def destination(self) -> str | None: ...
    @property
    def in_response_to(self) -> str | None: ...
    @property
    def issuer(self) -> Issuer | None: ...
    @property
    def has_signature(self) -> bool: ...
    @property
    def status(self) -> Status: ...
    def is_success(self) -> bool: ...
    @property
    def assertions(self) -> list[Assertion]: ...
    @property
    def encrypted_assertion_count(self) -> int: ...
    def to_xml(self) -> str: ...

class LogoutRequest:
    @property
    def id(self) -> str: ...
    @property
    def issue_instant(self) -> datetime: ...
    @property
    def destination(self) -> str | None: ...
    @property
    def issuer(self) -> Issuer | None: ...
    @property
    def reason(self) -> str | None: ...
    @property
    def name_id(self) -> NameId | None: ...
    @property
    def session_indexes(self) -> list[str]: ...
    def to_xml(self) -> str: ...

class LogoutResponse:
    @property
    def id(self) -> str: ...
    @property
    def in_response_to(self) -> str | None: ...
    @property
    def issuer(self) -> Issuer | None: ...
    @property
    def status(self) -> Status: ...
    def is_success(self) -> bool: ...
    def to_xml(self) -> str: ...
