class KeysManager:
    def __init__(self) -> None: ...
    @staticmethod
    def build_sp(private_key_pem: bytes, idp_certificate_pem: bytes) -> KeysManager: ...
    @staticmethod
    def build_idp(private_key_pem: bytes) -> KeysManager: ...
    def add_key_pem(self, pem: bytes, usage: str = ..., password: str | None = ...) -> None: ...
    def add_trusted_cert(self, cert: bytes) -> None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...

class SamlSigner:
    def __init__(self, keys: KeysManager) -> None: ...
    @staticmethod
    def from_pem(private_key_pem: bytes, password: str | None = ...) -> SamlSigner: ...
    @staticmethod
    def with_pkcs11(signer: Pkcs11Signer, keys: KeysManager | None = ...) -> SamlSigner: ...
    def sign_enveloped(self, xml_with_template: str) -> str: ...
    def sign_redirect_query(self, query_string: bytes, algorithm_uri: str, unsafe_allow_weak_sha1: bool = ...) -> bytes: ...
    def signature_method_uri(self) -> str: ...
    def is_hsm_backed(self) -> bool: ...

class VerifyResult:
    def is_valid(self) -> bool: ...
    def __bool__(self) -> bool: ...
    @property
    def reason(self) -> str | None: ...
    def signed_reference_ids(self) -> list[str]: ...
    def signing_cert_chain(self) -> list[bytes]: ...

class SamlVerifier:
    def __init__(self, keys: KeysManager) -> None: ...
    @staticmethod
    def from_cert(cert: bytes) -> SamlVerifier: ...
    def set_skip_time_checks(self, skip: bool, unsafe_allow_skip_time_checks: bool = ...) -> None: ...
    def set_trusted_keys_only(self, trusted: bool, unsafe_allow_untrusted_keys: bool = ...) -> None: ...
    def set_strict_verification(self, strict: bool, unsafe_allow_non_strict: bool = ...) -> None: ...
    def set_hmac_min_out_len(self, bits: int) -> None: ...
    def verify_enveloped(self, signed_xml: str) -> VerifyResult: ...
    def verify_redirect_query(self, query_string: bytes, signature: bytes, algorithm_uri: str, unsafe_allow_weak_sha1: bool = ...) -> bool: ...

class SamlEncryptor:
    def __init__(self, keys: KeysManager) -> None: ...
    @staticmethod
    def for_certificate(cert_der: bytes) -> SamlEncryptor: ...
    def encrypt(self, template_xml: str, plaintext: bytes) -> str: ...

class SamlDecryptor:
    def __init__(self, keys: KeysManager) -> None: ...
    def decrypt(self, encrypted_xml: str) -> str: ...
    def decrypt_to_bytes(self, encrypted_xml: str) -> bytes: ...

class Pkcs11Provider:
    def __init__(self, module_path: str) -> None: ...
    def open_session(self, pin: str) -> Pkcs11Session: ...

class Pkcs11Session:
    def signer(self, key_label: str, algorithm: str, unsafe_allow_weak_sha1: bool = ...) -> Pkcs11Signer: ...

class Pkcs11Signer:
    def __init__(self, session: Pkcs11Session, key_label: str, algorithm: str, unsafe_allow_weak_sha1: bool = ...) -> None: ...

def canonicalize(xml: str, mode: str = ..., inclusive_prefixes: list[str] | None = ...) -> bytes: ...
def exc_c14n(xml: str, inclusive_prefixes: list[str] | None = ...) -> bytes: ...
