from .core import Assertion, Attribute, NameId, RequestedAuthnContext

class Eptid:
    def __init__(self, secret: str) -> None: ...
    def get(self, idp_entity_id: str, sp_entity_id: str, user_id: str) -> str: ...
    def name_id(self, idp_entity_id: str, sp_entity_id: str, user_id: str) -> NameId: ...
    def attribute(self, idp_entity_id: str, sp_entity_id: str, user_id: str) -> Attribute: ...

class AuthnMethod:
    @property
    def class_ref(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def level(self) -> int: ...
    @property
    def authn_authority(self) -> str | None: ...
    @property
    def reference(self) -> str: ...

class AuthnBroker:
    def __init__(self) -> None: ...
    def add(self, class_ref: str, method: str, level: int, authn_authority: str | None = ...) -> str: ...
    def get_by_class_ref(self, class_ref: str) -> AuthnMethod | None: ...
    def pick(self, requested: RequestedAuthnContext | None = ...) -> list[AuthnMethod]: ...

class InMemoryAssertionStore:
    def __init__(self) -> None: ...
    def store_assertion(self, assertion: Assertion) -> None: ...
    def get_assertion(self, assertion_id: str) -> Assertion | None: ...
    def assertions_for_subject(self, name_id_value: str) -> list[Assertion]: ...
    def remove_assertion(self, assertion_id: str) -> None: ...

def code_name_id(name_id: NameId) -> str: ...
def decode_name_id(coded: str) -> NameId: ...
