from datetime import datetime
from typing import Protocol

from .core import Assertion, Attribute, NameId, NameIdPolicy, RequestedAuthnContext
from .metadata import EntityDescriptor

COCO_V1: str
COCO_V2: str
REFEDS_RESEARCH_AND_SCHOLARSHIP: str
INCOMMON_RESEARCH_AND_SCHOLARSHIP: str
MYACADEMICID_ESI: str
REFEDS_PERSONALIZED: str
REFEDS_PSEUDONYMOUS: str
REFEDS_ANONYMOUS: str
AT_EGOV_PVP2: str
AT_EGOV_PVP2_CHARGE: str
ENTITY_CATEGORY_ATTR: str
SUBJECT_ID_ATTR: str
PAIRWISE_ID_ATTR: str
SUBJECT_ID_REQ_ATTR: str

class IdentityStore(Protocol):
    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str) -> None: ...
    def remove(self, key: str) -> None: ...

class Eptid:
    def __init__(self, secret: str) -> None: ...
    def get(self, idp_entity_id: str, sp_entity_id: str, user_id: str) -> str: ...
    def name_id(self, idp_entity_id: str, sp_entity_id: str, user_id: str) -> NameId: ...
    def attribute(self, idp_entity_id: str, sp_entity_id: str, user_id: str) -> Attribute: ...

class AuthnMethod:
    @property
    def class_ref(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def level(self) -> int: ...
    @property
    def authn_authority(self) -> str | None: ...
    @property
    def reference(self) -> str: ...

class AuthnBroker:
    def __init__(self) -> None: ...
    def add(self, class_ref: str, method: str, level: int, authn_authority: str | None = ...) -> str: ...
    def get_by_class_ref(self, class_ref: str) -> AuthnMethod | None: ...
    def pick(self, requested: RequestedAuthnContext | None = ...) -> list[AuthnMethod]: ...

class InMemoryAssertionStore:
    def __init__(self) -> None: ...
    def store_assertion(self, assertion: Assertion) -> None: ...
    def get_assertion(self, assertion_id: str) -> Assertion | None: ...
    def assertions_for_subject(self, name_id_value: str) -> list[Assertion]: ...
    def remove_assertion(self, assertion_id: str) -> None: ...

class IdentDb:
    def __init__(
        self,
        idp_entity_id: str,
        store: IdentityStore | None = ...,
        domain: str | None = ...,
    ) -> None: ...
    def store(self, user_id: str, name_id: NameId) -> None: ...
    def find_local_id(self, name_id: NameId) -> str | None: ...
    def name_ids_for(self, user_id: str) -> list[NameId]: ...
    def match_local_id(
        self,
        user_id: str,
        sp_name_qualifier: str | None = ...,
        name_qualifier: str | None = ...,
    ) -> NameId | None: ...
    def transient_nameid(self, user_id: str, sp_name_qualifier: str | None = ...) -> NameId: ...
    def persistent_nameid(self, user_id: str, sp_name_qualifier: str | None = ...) -> NameId: ...
    def construct_nameid(
        self,
        user_id: str,
        sp_entity_id: str,
        name_id_policy: NameIdPolicy | None = ...,
        default_format: str | None = ...,
    ) -> NameId: ...
    def manage_name_id_new_id(self, name_id: NameId, new_id: str) -> NameId: ...
    def manage_name_id_terminate(self, name_id: NameId) -> NameId: ...
    def handle_name_id_mapping_request(
        self, name_id: NameId, name_id_policy: NameIdPolicy
    ) -> NameId: ...
    def remove_remote(self, name_id: NameId) -> None: ...
    def remove_local(self, user_id: str) -> None: ...

class EntityCategoryRule:
    def __init__(
        self,
        categories: list[str],
        attributes: list[str],
        conflicts: list[str] | None = ...,
        only_required: bool = ...,
    ) -> None: ...
    @property
    def categories(self) -> list[str]: ...
    @property
    def attributes(self) -> list[str]: ...
    @property
    def conflicts(self) -> list[str]: ...
    @property
    def only_required(self) -> bool: ...

class EntityCategoryPolicy:
    def __init__(
        self,
        name: str,
        rules: list[EntityCategoryRule] | None = ...,
        extend: str | None = ...,
    ) -> None: ...
    @staticmethod
    def shipped(name: str) -> EntityCategoryPolicy: ...
    @property
    def name(self) -> str: ...

class SignTargets:
    def __init__(
        self, response: bool = ..., assertion: bool = ..., on_demand: bool = ...
    ) -> None: ...
    @property
    def response(self) -> bool: ...
    @property
    def assertion(self) -> bool: ...
    @property
    def on_demand(self) -> bool: ...
    def resolve(self, sp_wants_assertions_signed: bool) -> ResolvedSignTargets: ...

class ResolvedSignTargets:
    @property
    def sign_response(self) -> bool: ...
    @property
    def sign_assertion(self) -> bool: ...

class PolicyEntry:
    def __init__(
        self,
        nameid_format: str | None = ...,
        name_form: str | None = ...,
        lifetime_seconds: int | None = ...,
        sign: SignTargets | None = ...,
        fail_on_missing_requested: bool | None = ...,
        entity_categories: list[str] | None = ...,
        owned_entity_categories: list[EntityCategoryPolicy] | None = ...,
        attribute_restrictions: list[tuple[str, list[str] | None]] | None = ...,
    ) -> None: ...

class ReleasePolicy:
    def __init__(self, default: PolicyEntry | None = ...) -> None: ...
    def insert(self, sp_entity_id: str, entry: PolicyEntry) -> None: ...
    def set_registration_authority(
        self, sp_entity_id: str, registration_authority: str
    ) -> None: ...
    def register_sp_metadata(self, entity: EntityDescriptor) -> None: ...
    def nameid_format(self, sp_entity_id: str) -> str: ...
    def name_form(self, sp_entity_id: str) -> str: ...
    def lifetime_seconds(self, sp_entity_id: str) -> int: ...
    def not_on_or_after(self, sp_entity_id: str, now: datetime) -> datetime: ...
    def sign(self, sp_entity_id: str) -> SignTargets: ...
    def fail_on_missing_requested(self, sp_entity_id: str) -> bool: ...
    def filter(
        self,
        attributes: list[Attribute],
        sp_entity_id: str,
        sp_entity_categories: list[str] | None = ...,
        required: list[Attribute] | None = ...,
        optional: list[Attribute] | None = ...,
        subject_id_req: str = ...,
    ) -> list[Attribute]: ...

def releasable_attributes(
    policies: list[EntityCategoryPolicy],
    sp_entity_categories: list[str],
    required_local_names: list[str] | None = ...,
) -> list[str]: ...
def subject_id_req_from_metadata(values: list[str]) -> str: ...
def code_name_id(name_id: NameId) -> str: ...
def decode_name_id(coded: str) -> NameId: ...
