from datetime import datetime

from .core import LogoutRequest, LogoutResponse, NameId

REASON_USER: str
REASON_ADMIN: str

class SpLogoutRequestOptions:
    def __init__(
        self,
        sp_entity_id: str,
        name_id: NameId,
        session_indexes: list[str] | None = ...,
        reason: str | None = ...,
        destination: str | None = ...,
        not_on_or_after: datetime | None = ...,
    ) -> None: ...

class LogoutTarget:
    def __init__(
        self,
        entity_id: str,
        name_id: NameId,
        slo_url: str,
        slo_binding: str,
        session_indexes: list[str] | None = ...,
    ) -> None: ...
    @property
    def entity_id(self) -> str: ...
    @property
    def slo_url(self) -> str: ...
    @property
    def slo_binding(self) -> str: ...
    @property
    def session_indexes(self) -> list[str]: ...

class PendingLogoutRequest:
    @property
    def entity_id(self) -> str: ...
    @property
    def request(self) -> LogoutRequest: ...
    @property
    def binding(self) -> str: ...
    @property
    def destination(self) -> str: ...

class LogoutResponseOutcome:
    @property
    def entity_id(self) -> str: ...
    @property
    def success(self) -> bool: ...
    @property
    def partial(self) -> bool: ...

class TargetLogoutState:
    @property
    def kind(self) -> str: ...
    @property
    def request_id(self) -> str | None: ...
    @property
    def reason(self) -> str | None: ...

class LogoutPropagationResult:
    @property
    def total_participants(self) -> int: ...
    @property
    def successful_logouts(self) -> int: ...
    @property
    def failed_participants(self) -> list[str]: ...
    def is_complete(self) -> bool: ...
    def is_partial(self) -> bool: ...

class SpLogoutOrchestrator:
    def __init__(self, sp_entity_id: str, reason: str | None = ...) -> None: ...
    def add_target(self, target: LogoutTarget) -> None: ...
    def next_request(self) -> PendingLogoutRequest | None: ...
    def handle_response(self, response: LogoutResponse) -> LogoutResponseOutcome: ...
    def mark_failed(self, entity_id: str, failure_reason: str) -> None: ...
    def target_state(self, entity_id: str) -> TargetLogoutState | None: ...
    def is_complete(self) -> bool: ...
    def progress(self) -> LogoutPropagationResult: ...

def create_sp_logout_request(options: SpLogoutRequestOptions) -> LogoutRequest: ...
def create_logout_response_success(
    entity_id: str, in_response_to: str, destination: str | None = ...
) -> LogoutResponse: ...
def create_logout_response_partial(
    entity_id: str, in_response_to: str, destination: str | None = ...
) -> LogoutResponse: ...
def create_logout_response_error(
    entity_id: str,
    in_response_to: str,
    status_code: str,
    status_message: str | None = ...,
    destination: str | None = ...,
) -> LogoutResponse: ...
def validate_logout_request(
    request: LogoutRequest, now: datetime, clock_skew_seconds: int = ...
) -> None: ...
