from .core import Attribute

class UiLogo:
    @property
    def url(self) -> str: ...
    @property
    def width(self) -> int | None: ...
    @property
    def height(self) -> int | None: ...
    @property
    def lang(self) -> str | None: ...

class UiInfo:
    @property
    def display_names(self) -> list[tuple[str | None, str]]: ...
    @property
    def descriptions(self) -> list[tuple[str | None, str]]: ...
    @property
    def information_urls(self) -> list[tuple[str | None, str]]: ...
    @property
    def privacy_statement_urls(self) -> list[tuple[str | None, str]]: ...
    @property
    def keywords(self) -> list[tuple[str | None, str]]: ...
    @property
    def logos(self) -> list[UiLogo]: ...

class EndpointInfo:
    @property
    def binding(self) -> str: ...
    @property
    def location(self) -> str: ...
    @property
    def response_location(self) -> str | None: ...
    @property
    def index(self) -> int | None: ...
    @property
    def is_default(self) -> bool | None: ...

class EntityDescriptor:
    @property
    def entity_id(self) -> str: ...
    @property
    def valid_until(self) -> object | None: ...
    @property
    def has_signature(self) -> bool: ...
    def is_idp(self) -> bool: ...
    def is_sp(self) -> bool: ...
    def single_sign_on_services(self) -> list[EndpointInfo]: ...
    def assertion_consumer_services(self) -> list[EndpointInfo]: ...
    def single_logout_services(self, role: str = ...) -> list[EndpointInfo]: ...
    def name_id_formats(self, role: str = ...) -> list[str]: ...
    def signing_certificates(self, role: str = ...) -> list[bytes]: ...
    def encryption_certificates(self, role: str = ...) -> list[bytes]: ...
    @property
    def registration_authority(self) -> str | None: ...
    def entity_categories(self) -> list[str]: ...
    def entity_attribute_values(self, name: str) -> list[str]: ...
    def entity_attributes(self) -> list[tuple[str, list[str]]]: ...
    def supported_algorithms(self) -> list[str]: ...
    def ui_info(self, role: str = ...) -> UiInfo | None: ...
    def requested_attributes(
        self, acs_index: int | None = ...
    ) -> tuple[list[Attribute], list[Attribute]]: ...
    def to_xml(self) -> str: ...

def parse_entity(xml: str) -> EntityDescriptor: ...
def parse_entities(xml: str) -> list[EntityDescriptor]: ...
def validate_entity(entity: EntityDescriptor) -> None: ...
