class EndpointInfo:
    @property
    def binding(self) -> str: ...
    @property
    def location(self) -> str: ...
    @property
    def response_location(self) -> str | None: ...
    @property
    def index(self) -> int | None: ...
    @property
    def is_default(self) -> bool | None: ...

class EntityDescriptor:
    @property
    def entity_id(self) -> str: ...
    @property
    def valid_until(self) -> object | None: ...
    @property
    def has_signature(self) -> bool: ...
    def is_idp(self) -> bool: ...
    def is_sp(self) -> bool: ...
    def single_sign_on_services(self) -> list[EndpointInfo]: ...
    def assertion_consumer_services(self) -> list[EndpointInfo]: ...
    def single_logout_services(self, role: str = ...) -> list[EndpointInfo]: ...
    def name_id_formats(self, role: str = ...) -> list[str]: ...
    def signing_certificates(self, role: str = ...) -> list[bytes]: ...
    def encryption_certificates(self, role: str = ...) -> list[bytes]: ...
    def to_xml(self) -> str: ...

def parse_entity(xml: str) -> EntityDescriptor: ...
def parse_entities(xml: str) -> list[EntityDescriptor]: ...
def validate_entity(entity: EntityDescriptor) -> None: ...
