from .core import Assertion, AuthnRequest, LogoutRequest, LogoutResponse, Response

def parse_response(xml: str) -> Response: ...
def parse_authn_request(xml: str) -> AuthnRequest: ...
def parse_assertion(xml: str) -> Assertion: ...
def parse_logout_request(xml: str) -> LogoutRequest: ...
def parse_logout_response(xml: str) -> LogoutResponse: ...
